# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - "enhancement" # Use this for breaking changes

    - title: 🚀 New Features
      labels:
        - "enhancement" # Use this for new features

    - title: 🐛 Bugfixes
      labels:
        - "bug"

    - title: 🪦 Deprecations
      labels:
        - "wontfix" # Use this for deprecations

    - title: 🛠️ Maintenance
      labels:
        - "dependencies"
        - "github_actions"

    - title: 📝 Documentation
      labels:
        - "documentation"

    - title: 🏷 Other Changes
      labels:
        - "*"