linters:
  presets:
    - bugs
    - error
    - performance
  enable:
    - gofmt
    - gofumpt
    - revive
    - gocyclo
    - misspell
    - whitespace
    - goimports
    - gosec
    - lll
  disable:
    - rowserrcheck
    - sqlclosecheck
    - wrapcheck
    - perfsprint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - err113