name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.token.outputs.token }}
      - if: steps.release.outputs.release_created
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.token.outputs.token }}
          script: |
            const tag = '${{ steps.release.outputs.tag_name }}';

            // Create annotated tag
            const result = await github.rest.git.createTag({
              ...context.repo,
              tag,
              message: `Release ${tag}`,
              type: 'commit',
              object: context.sha,
            });
            const sha = result.data.sha;

            // Create the ref
            await github.rest.git.createRef({
              ...context.repo,
              sha,
              ref: `refs/tags/${tag}`,
            });

            core.setOutput('sha', sha);